NDefines.NGame.START_DATE = "1984.1.1.12"
NDefines.NGame.END_DATE = "1999.1.1.1"

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 60
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36
NDefines.NGame.GAME_SPEED_SECONDS = { 0.35, 0.15, 0.1, 0.035, 0.0 }

NDefines.NDiplomacy.ENSION_TIME_SCALE_START_DATE = "1999.1.1.1"

NDefines.NAir.ACCIDENT_CHANCE_BALANCE_MULT = 0.10
NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_ACCIDENT_FACTOR = 1.2
NDefines.NAir.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.001
NDefines.NAir.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.004
NDefines.NAir.WAR_SCORE_GAIN_FOR_SUNK_CONVOY = 0.05		
NDefines.NAir.WAR_SCORE_DECAY_FOR_BUILT_CONVOY = 0.03

NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

NDefines.NAI.EQUIPMENT_MARKET_BASE_MARKET_RATIO = 0.35

Nlua = {

NTopbar = {
	GAME_SPEED_LIMIT = 0,
	GAME_SPEED_STEPS = 5,
	GAME_SPEED_ONE = 1,
	GAME_SPEED_TWO = 2,
	GAME_SPEED_THREE = 3,
	GAME_SPEED_FOUR = 4,
	GAME_SPEED_FIVE = 5,
	}
}